version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
        - ./.env

    networks:
      - docker-node-postgres
      - docker-node-mongodb
    command: npm run dev
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gobarber
      MONGO_INITDB_ROOT_PASSWORD: gobarber
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - docker-node-mongodb

  postgresql:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - docker-node-postgres:/var/lib/postgresql/data
    networks:
      - docker-node-postgres

volumes:
  docker-node-postgres:
  mongodb-data:
    driver: local

networks:
  docker-node-postgres:
  docker-node-mongodb:
  api:
    driver: bridge
